name: Build Android

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Install dependencies
        run: npm install

      - name: Generate native project
        run: npx expo prebuild --platform android --non-interactive

      - name: Build APK
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: chinchon-android-${{ inputs.version }}.apk
          path: android/app/build/outputs/apk/release/app-release.apk
