name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    needs: release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Web Build artifact
        uses: actions/download-artifact@v4
        with:
          name: chinchon-web-${{ needs.release.outputs.version }}.zip
          path: ./web-build

      - name: Extract Web Build
        run: unzip ./web-build/chinchon-web-${{ needs.release.outputs.version }}.zip -d ./dist

      - name: Set custom domain
        run: echo -n "chinchon.urbieta.dev" > ./dist/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
