name: Deploy to GitHub Pages

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Web Build artifact
        uses: actions/download-artifact@v4
        with:
          name: chinchon-web-${{ inputs.version }}.zip
          path: ./web-build
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Web Build
        run: |
          cd ./web-build
          unzip chinchon-web-${{ inputs.version }}.zip -d ../dist

      - name: Set custom domain
        run: echo -n "chinchon.urbieta.dev" > ./dist/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
