name: Release

on:
  push:
    branches:
      - main

jobs:
  build-web:
    uses: ./.github/workflows/web.yml

  build-android:
    uses: ./.github/workflows/android.yml

  release:
    needs: [build-web, build-android]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Download Android APK artifact
        uses: actions/download-artifact@v7
        with:
          name: chinchon-android
          path: ./artifacts/android

      - name: Download Web Build artifact
        uses: actions/download-artifact@v7
        with:
          name: chinchon-web
          path: ./artifacts/web

      - name: Package Web build
        run: |
          cd artifacts/web
          zip -r ../chinchon-web.zip .

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: "24"
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Release
        run: npx semantic-release

  deploy:
    needs: build-web
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Download Web Build artifact
        uses: actions/download-artifact@v7
        with:
          name: chinchon-web
          path: ./dist

      - name: Set custom domain
        run: echo -n "chinchon.urbieta.dev" > ./dist/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
