name: Build Web

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build Web
        run: npx expo export --platform web

      - name: Upload Web Build artifact
        uses: actions/upload-artifact@v4
        with:
          name: chinchon-web-${{ inputs.version }}.zip
          path: dist
